meta_product_name: "FurreverFriends"
meta_title: "FurreverFriends - Answer a quiz in order to determine which dog breed is best suited for you and live a happy life with your furryFriend"
meta_description: "Determine which breed is best suited for you and live a happy life with your furryFriend"
meta_image: "FurrEverFriends.png" # should exist in `app/assets/images/`
