meta_product_name: “FurreverFriends”

meta_title: “FurreverFriends – Find the best dog breed suited to your lifestyle”

meta_description: “Determine which breed is best suited for you and live a happy life with your furryFriend”

meta_url: “http://furreverfriends.pro”

meta_type: “website”

meta_image: “FurrEverFriends.png” # should exist in `app/assets/images/`
